<?php
declare(strict_types=1);
require_once __DIR__.'/config.php';
require_once __DIR__.'/db.php';
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, X-API-KEY, Authorization');
$origin=$_SERVER['HTTP_ORIGIN']??'';
$allowed=['https://internationalcassavacenter.com','https://www.internationalcassavacenter.com'];
if($origin && in_array($origin,$allowed,true)){header('Access-Control-Allow-Origin: '.$origin);header('Vary: Origin');}
if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
function apiKey():string{foreach(['HTTP_X_API_KEY','HTTP_AUTHORIZATION'] as $k){if(!empty($_SERVER[$k]))return preg_replace('/^Bearer\s+/i','',(string)$_SERVER[$k]);}return (string)($_GET['key']??'');}
function requireKey():void{if(!hash_equals((string)APP_API_KEY,apiKey()))jsonOut(['success'=>false,'error'=>'Unauthorized.'],401);}
function body():array{$raw=file_get_contents('php://input');$j=json_decode($raw,true);return is_array($j)?$j:[];}
function jsonOut(array $x,int $code=200):never{http_response_code($code);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function ensureDirs():void{foreach([MEDIA_DIR,BACKUP_DIR,__DIR__.'/storage/signatures'] as $d)if(!is_dir($d))@mkdir($d,0755,true);}
function token():string{return bin2hex(random_bytes(32));}
function sessionToken():string{return preg_replace('/^Bearer\s+/i','',(string)($_SERVER['HTTP_AUTHORIZATION']??''));}
function sessionUser(PDO $pdo,string $token):?array{if(!$token)return null;$h=hash('sha256',$token);$st=$pdo->prepare("SELECT s.*,u.username,u.name,u.jabatan,u.role,u.aktif FROM api_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>NOW() LIMIT 1");$st->execute([$h]);$r=$st->fetch();return $r?:null;}
function requireSession(PDO $pdo):array{$u=sessionUser($pdo,sessionToken());if(!$u||!(int)$u['aktif'])jsonOut(['success'=>false,'error'=>'Sesi tidak valid atau akun nonaktif.'],401);return $u;}
function isOwner(array $u):bool{return in_array((string)$u['role'],['master','owner'],true);}
function audit(PDO $pdo,string $action,array $u,array $details=[]):void{$st=$pdo->prepare("INSERT INTO audit_logs(actor,actor_role,action,page,ip,user_agent,details) VALUES(?,?,?,?,?,?,?)");$st->execute([$u['username'],$u['role'],$action,$details['page']??'api',$_SERVER['REMOTE_ADDR']??'',substr($_SERVER['HTTP_USER_AGENT']??'',0,500),json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}
function permission(PDO $pdo,array $u,string $key):bool{if(isOwner($u))return true;$st=$pdo->prepare("SELECT can_access FROM menu_permissions WHERE user_id=? AND menu_key=? LIMIT 1");$st->execute([$u['id'],$key]);return (bool)$st->fetchColumn();}
function requirePermission(PDO $pdo,array $u,string $key):void{if(!permission($pdo,$u,$key))jsonOut(['success'=>false,'error'=>'Akses ditolak: '.$key],403);}
function loadState(PDO $pdo):array{$r=$pdo->query("SELECT id,data,updated_at FROM erp_data WHERE id=1 LIMIT 1")->fetch();return $r?['data'=>$r['data'],'revision'=>(int)$r['id'],'updated_at'=>$r['updated_at']]:['data'=>null,'revision'=>0,'updated_at'=>null];}
function employeeRow(array $r):array{return ['id'=>(int)$r['id'],'employee_code'=>$r['employee_code'],'name'=>$r['name'],'nik'=>$r['nik']??null,'gender'=>$r['gender']??null,'birth_place'=>$r['birth_place']??null,'birth_date'=>$r['birth_date']??null,'address'=>$r['address']??null,'phone'=>$r['phone']??null,'email'=>$r['email']??null,'department'=>$r['department'],'position'=>$r['position'],'employment_status'=>$r['employment_status']??$r['status'],'joined_at'=>$r['joined_at'],'left_at'=>$r['left_at']??null,'salary'=>(float)$r['salary'],'bank_name'=>$r['bank_name']??null,'bank_account'=>$r['bank_account']??null,'npwp'=>$r['npwp']??null,'bpjs'=>$r['bpjs']??null,'photo'=>$r['photo']??null,'note'=>$r['note']??null,'status'=>$r['status']];}
try{
 $method=$_SERVER['REQUEST_METHOD'];$b=$method==='POST'?body():[];$action=(string)($b['action']??($_GET['action']??'load'));
 if($action==='login'){
  requireKey();$username=strtolower(trim((string)($b['username']??'')));$password=(string)($b['password']??'');if($username===''||$password==='')jsonOut(['success'=>false,'error'=>'Username dan password wajib diisi.'],400);
  $st=$pdo->prepare('SELECT * FROM users WHERE LOWER(username)=? LIMIT 1');$st->execute([$username]);$usr=$st->fetch();
  if(!$usr){$state=loadState($pdo);$d=$state['data']?json_decode($state['data'],true):[];$rec=$d['users'][$username]??null;if($rec&&isset($rec['password'])&&hash_equals((string)$rec['password'],$password)){ $hash=password_hash($password,PASSWORD_DEFAULT);$ins=$pdo->prepare('INSERT INTO users(username,name,jabatan,role,password_hash,aktif,signature_checklist_enabled) VALUES(?,?,?,?,?,?,?)');$role=($rec['role']??'division')==='master'?'master':(($rec['role']??'division')==='admin'?'admin':'division');$ins->execute([$username,$rec['name']??$username,$rec['jabatan']??null,$role,$hash,($rec['aktif']??true)?1:0,($rec['signatureChecklistEnabled']??false)?1:0]);$st->execute([$username]);$usr=$st->fetch();}}
  if(!$usr)jsonOut(['success'=>false,'error'=>'Username atau password salah.'],401);
  $valid=password_verify($password,(string)$usr['password_hash']);if(!$valid&&preg_match('/^[a-f0-9]{64}$/i',(string)$usr['password_hash'])&&hash_equals(strtolower((string)$usr['password_hash']),hash('sha256',$password))){$valid=true;$pdo->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$usr['id']]);}
  if(!$valid)jsonOut(['success'=>false,'error'=>'Username atau password salah.'],401);if(!(int)$usr['aktif'])jsonOut(['success'=>false,'error'=>'Akun dinonaktifkan.'],403);
  $deviceId=trim((string)($b['device_id']??''));$binding=(bool)$pdo->query("SELECT setting_value FROM app_settings WHERE setting_key='device_binding_enabled' LIMIT 1")->fetchColumn();
  if($binding){$ds=$pdo->prepare("SELECT id FROM devices WHERE user_id=? AND device_id=? AND status='active' LIMIT 1");$ds->execute([$usr['id'],$deviceId]);if(!$deviceId||!$ds->fetchColumn())jsonOut(['success'=>false,'error'=>'Perangkat belum diotorisasi Owner.','device_required'=>true],403);}
  $t=token();$st=$pdo->prepare("INSERT INTO api_sessions(user_id,token_hash,expires_at,ip,user_agent) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 8 HOUR),?,?)");$st->execute([$usr['id'],hash('sha256',$t),$_SERVER['REMOTE_ADDR']??'',substr($_SERVER['HTTP_USER_AGENT']??'',0,500)]);audit($pdo,'login',['id'=>$usr['id'],'username'=>$usr['username'],'role'=>$usr['role'],'page'=>'login'],[]);
  jsonOut(['success'=>true,'ok'=>true,'token'=>$t,'user'=>['id'=>(int)$usr['id'],'user'=>$usr['username'],'name'=>$usr['name'],'jabatan'=>$usr['jabatan'],'role'=>$usr['role'],'page'=>$usr['role']==='master'?'owner':($usr['role']==='admin'?'admin':'division')]]);
 }
 if($action==='logout'){requireKey();$tok=sessionToken()?:trim((string)($b['token']??''));if($tok)$pdo->prepare('DELETE FROM api_sessions WHERE token_hash=?')->execute([hash('sha256',$tok)]);jsonOut(['success'=>true,'ok'=>true]);}
 requireKey();
 if($action==='load'){$s=loadState($pdo);jsonOut(['success'=>true,'ok'=>true,'value'=>$s['data'],'revision'=>$s['revision'],'updated_at'=>$s['updated_at']]);}
 if($action==='meta'){$s=loadState($pdo);jsonOut(['success'=>true,'ok'=>true,'revision'=>$s['revision'],'updated_at'=>$s['updated_at']]);}
 $u=requireSession($pdo);
 if($action==='save'){ $value=$b['value']??null;if(!is_string($value)||$value==='')jsonOut(['success'=>false,'error'=>'JSON value wajib diisi.'],400);json_decode($value);if(json_last_error()!==JSON_ERROR_NONE)jsonOut(['success'=>false,'error'=>'JSON tidak valid.'],400);$pdo->beginTransaction();$st=$pdo->prepare('INSERT INTO erp_data(id,data) VALUES(1,?) ON DUPLICATE KEY UPDATE data=VALUES(data),updated_at=CURRENT_TIMESTAMP');$st->execute([$value]);audit($pdo,'save',$u,['page'=>$b['page']??'erp']);$pdo->commit();$s=loadState($pdo);jsonOut(['success'=>true,'ok'=>true,'revision'=>$s['revision'],'updated_at'=>$s['updated_at']]);}
 if($action==='users_list'){requirePermission($pdo,$u,'manage_users');$rows=$pdo->query("SELECT id,username,name,jabatan,role,aktif,created_at,updated_at FROM users ORDER BY role,id")->fetchAll();jsonOut(['success'=>true,'items'=>$rows]);}
 if($action==='user_save'){requirePermission($pdo,$u,'manage_users');$id=(int)($b['id']??0);$username=strtolower(trim((string)($b['username']??'')));$name=trim((string)($b['name']??''));$role=(string)($b['role']??'division');$jabatan=trim((string)($b['jabatan']??''));$aktif=!empty($b['aktif'])?1:0;if($username===''||$name==='')jsonOut(['success'=>false,'error'=>'Username dan nama wajib.'],400);if(!in_array($role,['master','admin','division'],true))jsonOut(['success'=>false,'error'=>'Role tidak valid.'],400);if(!$id){$password=(string)($b['password']??'');if(strlen($password)<8)jsonOut(['success'=>false,'error'=>'Password minimal 8 karakter.'],400);$cnt=$pdo->prepare('SELECT COUNT(*) FROM users WHERE role=?');$cnt->execute([$role]);$n=(int)$cnt->fetchColumn();if($role==='master'&&$n>=1)jsonOut(['success'=>false,'error'=>'Maksimal 1 Owner/Master.'],409);if($role==='admin'&&$n>=10)jsonOut(['success'=>false,'error'=>'Maksimal 10 Admin.'],409);if($role==='division'&&$n>=10)jsonOut(['success'=>false,'error'=>'Maksimal 10 Devisi.'],409);$st=$pdo->prepare('INSERT INTO users(username,name,jabatan,role,password_hash,aktif) VALUES(?,?,?,?,?,?)');$st->execute([$username,$name,$jabatan,$role,password_hash($password,PASSWORD_DEFAULT),$aktif]);$id=(int)$pdo->lastInsertId();audit($pdo,'user_created',$u,['id'=>$id]);}else{$st=$pdo->prepare('UPDATE users SET username=?,name=?,jabatan=?,role=?,aktif=? WHERE id=?');$st->execute([$username,$name,$jabatan,$role,$aktif,$id]);if((string)($b['password']??'')!=='')$pdo->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash((string)$b['password'],PASSWORD_DEFAULT),$id]);audit($pdo,'user_updated',$u,['id'=>$id]);}jsonOut(['success'=>true,'id'=>$id]);}
 if($action==='user_delete'){requirePermission($pdo,$u,'manage_users');$id=(int)($b['id']??0);if($id===(int)$u['id'])jsonOut(['success'=>false,'error'=>'Owner tidak dapat menghapus akun sendiri.'],400);$pdo->prepare('UPDATE users SET aktif=0 WHERE id=?')->execute([$id]);audit($pdo,'user_disabled',$u,['id'=>$id]);jsonOut(['success'=>true]);}
 if($action==='permissions_get'){requirePermission($pdo,$u,'manage_users');$uid=(int)($b['user_id']??0);$st=$pdo->prepare('SELECT menu_key,can_access FROM menu_permissions WHERE user_id=? ORDER BY menu_key');$st->execute([$uid]);jsonOut(['success'=>true,'items'=>$st->fetchAll()]);}
 if($action==='permissions_save'){requirePermission($pdo,$u,'manage_users');$uid=(int)($b['user_id']??0);$items=is_array($b['items']??null)?$b['items']:[];$pdo->beginTransaction();$del=$pdo->prepare('DELETE FROM menu_permissions WHERE user_id=?');$del->execute([$uid]);$ins=$pdo->prepare('INSERT INTO menu_permissions(user_id,menu_key,can_access) VALUES(?,?,?)');foreach($items as $x){$key=preg_replace('/[^a-zA-Z0-9_.:-]/','',(string)($x['menu_key']??''));if($key!=='')$ins->execute([$uid,$key,!empty($x['can_access'])?1:0]);}audit($pdo,'permission_changed',$u,['user_id'=>$uid]);$pdo->commit();jsonOut(['success'=>true]);}
 if($action==='device_list'){requirePermission($pdo,$u,'manage_devices');$rows=$pdo->query("SELECT d.id,d.user_id,d.device_id,d.device_name,d.platform,d.status,d.registered_at,d.last_login_at,u.username,u.name,u.role FROM devices d JOIN users u ON u.id=d.user_id ORDER BY d.id DESC")->fetchAll();jsonOut(['success'=>true,'items'=>$rows]);}
 if($action==='device_register'){ $uid=(int)($b['user_id']??$u['id']);if(!isOwner($u)&&$uid!==(int)$u['id'])jsonOut(['success'=>false,'error'=>'Tidak boleh mendaftarkan perangkat akun lain.'],403);$did=trim((string)($b['device_id']??''));if(strlen($did)<16)jsonOut(['success'=>false,'error'=>'Device ID tidak valid.'],400);$st=$pdo->prepare("INSERT INTO devices(user_id,device_id,device_name,platform,status,registered_at) VALUES(?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE device_name=VALUES(device_name),platform=VALUES(platform),status=VALUES(status)");$status=isOwner($u)?'active':'pending';$st->execute([$uid,$did,trim((string)($b['device_name']??'Perangkat')),trim((string)($b['platform']??'browser')),$status]);audit($pdo,'device_registered',$u,['user_id'=>$uid,'device_id'=>$did]);jsonOut(['success'=>true,'status'=>$status]);}
 if($action==='device_status'){requirePermission($pdo,$u,'manage_devices');$id=(int)($b['id']??0);$status=(string)($b['status']??'pending');if(!in_array($status,['pending','active','inactive','blocked'],true))jsonOut(['success'=>false,'error'=>'Status tidak valid.'],400);$pdo->prepare('UPDATE devices SET status=? WHERE id=?')->execute([$status,$id]);audit($pdo,'device_status_changed',$u,['id'=>$id,'status'=>$status]);jsonOut(['success'=>true]);}
 if($action==='employees_list'){requirePermission($pdo,$u,'view_employees');$st=$pdo->query('SELECT * FROM employees ORDER BY id DESC');$out=array_map('employeeRow',$st->fetchAll());jsonOut(['success'=>true,'items'=>$out]);}
 if($action==='employee_save'){requirePermission($pdo,$u,empty($b['id'])?'create_employees':'edit_employees');$id=(int)($b['id']??0);$fields=['employee_code','name','nik','gender','birth_place','birth_date','address','phone','email','department','position','employment_status','joined_at','left_at','salary','bank_name','bank_account','npwp','bpjs','photo','note','status'];$data=[];foreach($fields as $f)$data[$f]=$b[$f]??null;$data['name']=trim((string)$data['name']);if($data['name']==='')jsonOut(['success'=>false,'error'=>'Nama karyawan wajib.'],400);$data['salary']=(float)($data['salary']??0);$data['employment_status']=$data['employment_status']?:'aktif';$data['status']=in_array((string)$data['status'],['aktif','nonaktif'],true)?$data['status']:'aktif';if(!$id){$cols=implode(',',array_keys($data));$qs=implode(',',array_fill(0,count($data),'?'));$st=$pdo->prepare("INSERT INTO employees($cols) VALUES($qs)");$st->execute(array_values($data));$id=(int)$pdo->lastInsertId();audit($pdo,'employee_created',$u,['id'=>$id]);}else{$set=implode(',',array_map(fn($x)=>$x.'=?',array_keys($data)));$st=$pdo->prepare("UPDATE employees SET $set WHERE id=?");$vals=array_values($data);$vals[]=$id;$st->execute($vals);audit($pdo,'employee_updated',$u,['id'=>$id]);}jsonOut(['success'=>true,'id'=>$id]);}
 if($action==='employee_status'){requirePermission($pdo,$u,'edit_employees');$id=(int)($b['id']??0);$status=(string)($b['status']??'nonaktif');$pdo->prepare('UPDATE employees SET status=?,employment_status=? WHERE id=?')->execute([$status,$status,$id]);audit($pdo,'employee_status',$u,['id'=>$id,'status'=>$status]);jsonOut(['success'=>true]);}
 if($action==='payroll_list'){requirePermission($pdo,$u,'view_payroll');$where=[];$vals=[];foreach(['period','status'] as $f){if(($b[$f]??'')!==''){$where[]="$f=?";$vals[]=$b[$f];}}if(!empty($b['employee_id'])){$where[]='p.employee_id=?';$vals[]=(int)$b['employee_id'];}$sql="SELECT p.*,e.employee_code,e.name employee_name,e.department,e.position FROM payroll p JOIN employees e ON e.id=p.employee_id".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY p.period DESC,p.id DESC LIMIT 1000';$st=$pdo->prepare($sql);$st->execute($vals);jsonOut(['success'=>true,'items'=>$st->fetchAll()]);}
 if($action==='payroll_generate'){requirePermission($pdo,$u,'create_payroll');$period=preg_match('/^\d{4}-\d{2}$/',(string)($b['period']??''))?(string)$b['period']:'';if(!$period)jsonOut(['success'=>false,'error'=>'Periode YYYY-MM wajib.'],400);$emps=$pdo->query("SELECT * FROM employees WHERE status<>'nonaktif'")->fetchAll();$count=0;$pdo->beginTransaction();foreach($emps as $e){$ot=$pdo->prepare("SELECT COALESCE(SUM(hours*rate),0) FROM overtime WHERE employee_id=? AND DATE_FORMAT(work_date,'%Y-%m')=? AND status<>'ditolak'");$ot->execute([$e['id'],$period]);$overtime=(float)$ot->fetchColumn();$allowance=(float)($b['allowance']??0);$meal=(float)($b['meal']??0);$transport=(float)($b['transport']??0);$bonus=(float)($b['bonus']??0);$incentive=(float)($b['incentive']??0);$otherIncome=(float)($b['other_income']??0);$deduction=(float)($b['deduction']??0);$bpjs=(float)($b['bpjs']??0);$tax=(float)($b['tax']??0);$loan=(float)($b['loan']??0);$otherDed=(float)($b['other_deduction']??0);$income=(float)$e['salary']+$allowance+$meal+$transport+$overtime+$bonus+$incentive+$otherIncome;$totalDed=$deduction+$bpjs+$tax+$loan+$otherDed;$net=$income-$totalDed;$st=$pdo->prepare("INSERT INTO payroll(period,employee_id,basic,overtime,allowance,meal,transport,bonus,incentive,other_income,deduction,bpjs,tax,loan,other_deduction,total_income,total_deduction,net,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE basic=VALUES(basic),overtime=VALUES(overtime),allowance=VALUES(allowance),meal=VALUES(meal),transport=VALUES(transport),bonus=VALUES(bonus),incentive=VALUES(incentive),other_income=VALUES(other_income),deduction=VALUES(deduction),bpjs=VALUES(bpjs),tax=VALUES(tax),loan=VALUES(loan),other_deduction=VALUES(other_deduction),total_income=VALUES(total_income),total_deduction=VALUES(total_deduction),net=VALUES(net)");$st->execute([$period,$e['id'],$e['salary'],$overtime,$allowance,$meal,$transport,$bonus,$incentive,$otherIncome,$deduction,$bpjs,$tax,$loan,$otherDed,$income,$totalDed,$net,'draft']);$count++;}audit($pdo,'payroll_created',$u,['period'=>$period,'count'=>$count]);$pdo->commit();jsonOut(['success'=>true,'count'=>$count]);}
 if($action==='payroll_approve'){requirePermission($pdo,$u,'approve_payroll');$id=(int)($b['id']??0);$pdo->prepare("UPDATE payroll SET status='approved' WHERE id=?")->execute([$id]);audit($pdo,'payroll_approved',$u,['id'=>$id]);jsonOut(['success'=>true]);}
 if($action==='payslip_create'){requirePermission($pdo,$u,'create_payslip');$pid=(int)($b['payroll_id']??0);$st=$pdo->prepare("SELECT p.*,e.employee_code,e.name employee_name,e.department,e.position FROM payroll p JOIN employees e ON e.id=p.employee_id WHERE p.id=?");$st->execute([$pid]);$p=$st->fetch();if(!$p)jsonOut(['success'=>false,'error'=>'Payroll tidak ditemukan.'],404);$slip='SLIP-'.date('Ym').'-'.str_pad((string)$pid,6,'0',STR_PAD_LEFT);$st=$pdo->prepare('INSERT INTO payslips(payroll_id,slip_no) VALUES(?,?) ON DUPLICATE KEY UPDATE slip_no=VALUES(slip_no)');$st->execute([$pid,$slip]);$id=(int)$pdo->lastInsertId();audit($pdo,'payslip_created',$u,['payroll_id'=>$pid]);jsonOut(['success'=>true,'id'=>$id,'slip_no'=>$slip,'payroll'=>$p]);}
 if($action==='payslips_list'){requirePermission($pdo,$u,'view_payslip');$st=$pdo->query("SELECT s.*,p.period,p.employee_id,e.employee_code,e.name employee_name,e.department,e.position,p.basic,p.overtime,p.allowance,p.meal,p.transport,p.bonus,p.incentive,p.other_income,p.deduction,p.bpjs,p.tax,p.loan,p.other_deduction,p.total_income,p.total_deduction,p.net,p.status payroll_status FROM payslips s JOIN payroll p ON p.id=s.payroll_id JOIN employees e ON e.id=p.employee_id ORDER BY s.id DESC LIMIT 1000");jsonOut(['success'=>true,'items'=>$st->fetchAll()]);}
 if($action==='signatures_list'){requirePermission($pdo,$u,'signature');$rows=$pdo->query("SELECT * FROM signatures ORDER BY slot_no")->fetchAll();jsonOut(['success'=>true,'items'=>$rows]);}
 if($action==='signature_save'){requirePermission($pdo,$u,'signature');$id=(int)($b['id']??0);$slot=(int)($b['slot_no']??0);$name=trim((string)($b['name']??''));$jabatan=trim((string)($b['jabatan']??''));$ket=trim((string)($b['keterangan']??''));$active=!empty($b['active'])?1:0;$data=(string)($b['signature_data']??'');if($slot<1||$slot>6)jsonOut(['success'=>false,'error'=>'Slot tanda tangan harus 1-6.'],400);if($active){$cnt=$pdo->query("SELECT COUNT(*) FROM signatures WHERE active=1")->fetchColumn();$old=$id?$pdo->query('SELECT active FROM signatures WHERE id='.(int)$id)->fetchColumn():0;if((int)$cnt>=6&&!$old)jsonOut(['success'=>false,'error'=>'Maksimal 6 tanda tangan aktif.'],409);}if($data!==''&&!preg_match('#^data:image/png;base64,#',$data))jsonOut(['success'=>false,'error'=>'Tanda tangan harus PNG data URL.'],400);ensureDirs();$path=null;if($data!==''){ $raw=base64_decode(preg_replace('#^data:image/png;base64,#','',$data),true);if($raw===false||strlen($raw)>2*1024*1024)jsonOut(['success'=>false,'error'=>'File tanda tangan tidak valid atau terlalu besar.'],400);$path='storage/signatures/'.bin2hex(random_bytes(16)).'.png';file_put_contents(__DIR__.'/'.$path,$raw,LOCK_EX);}$oldPath=$id?$pdo->query('SELECT signature_path FROM signatures WHERE id='.(int)$id)->fetchColumn():null;$sql=$id?'UPDATE signatures SET slot_no=?,name=?,jabatan=?,keterangan=?,signature_path=COALESCE(?,signature_path),active=? WHERE id=?':'INSERT INTO signatures(slot_no,name,jabatan,keterangan,signature_path,active) VALUES(?,?,?,?,?,?)';$st=$pdo->prepare($sql);$id?$st->execute([$slot,$name,$jabatan,$ket,$path,$active,$id]):$st->execute([$slot,$name,$jabatan,$ket,$path,$active]);if($path&&$oldPath&&is_file(__DIR__.'/'.$oldPath))@unlink(__DIR__.'/'.$oldPath);audit($pdo,'signature_saved',$u,['id'=>$id,'slot'=>$slot,'active'=>$active]);jsonOut(['success'=>true]);}
 if($action==='signature_delete'){requirePermission($pdo,$u,'signature');$id=(int)($b['id']??0);$path=$pdo->query('SELECT signature_path FROM signatures WHERE id='.(int)$id)->fetchColumn();$pdo->prepare('DELETE FROM signatures WHERE id=?')->execute([$id]);if($path&&is_file(__DIR__.'/'.$path))@unlink(__DIR__.'/'.$path);audit($pdo,'signature_disabled',$u,['id'=>$id]);jsonOut(['success'=>true]);}
 if($action==='audit_list'){requirePermission($pdo,$u,'audit');$limit=max(1,min(500,(int)($b['limit']??100)));$st=$pdo->query("SELECT id,actor,actor_role AS role,action,page,created_at AS at,details FROM audit_logs ORDER BY id DESC LIMIT $limit");jsonOut(['success'=>true,'items'=>$st->fetchAll()]);}
 if($action==='reset_admin_division_passwords'){if(!isOwner($u))jsonOut(['success'=>false,'error'=>'Hanya Owner.'],403);$temp=bin2hex(random_bytes(6));$hash=password_hash($temp,PASSWORD_DEFAULT);$pdo->beginTransaction();$pdo->prepare("UPDATE users SET password_hash=? WHERE role IN ('admin','division')")->execute([$hash]);audit($pdo,'reset_admin_division_passwords',$u,['count'=>$pdo->rowCount()]);$pdo->commit();jsonOut(['success'=>true,'message'=>'Password Admin dan Devisi berhasil direset. Password sementara hanya ditampilkan sekali.','temporary_password'=>$temp]);}
if($action==='backup_create'){if(!isOwner($u))jsonOut(['success'=>false,'error'=>'Hanya Owner.'],403);ensureDirs();$snap=['created_at'=>date('c'),'erp_data'=>loadState($pdo),'users'=>$pdo->query('SELECT id,username,name,jabatan,role,aktif,created_at,updated_at FROM users')->fetchAll(),'employees'=>$pdo->query('SELECT * FROM employees')->fetchAll(),'payroll'=>$pdo->query('SELECT * FROM payroll')->fetchAll(),'signatures'=>$pdo->query('SELECT id,slot_no,name,jabatan,keterangan,signature_path,active FROM signatures')->fetchAll()];$json=json_encode($snap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$fn='backup_'.date('Ymd_His').'_'.bin2hex(random_bytes(3)).'.json';$st=$pdo->prepare("INSERT INTO system_backups(backup_type,actor,filename,payload) VALUES('manual',?,?,?)");$st->execute([$u['username'],$fn,$json]);file_put_contents(BACKUP_DIR.'/'.$fn,$json,LOCK_EX);audit($pdo,'backup_create',$u,['filename'=>$fn]);jsonOut(['success'=>true,'backup'=>['filename'=>$fn,'at'=>date('c'),'actor'=>$u['username']]]);}
 if($action==='settings_device_binding'){if(!isOwner($u))jsonOut(['success'=>false,'error'=>'Hanya Owner.'],403);$enabled=!empty($b['enabled'])?'1':'0';$st=$pdo->prepare("INSERT INTO app_settings(setting_key,setting_value) VALUES('device_binding_enabled',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");$st->execute([$enabled]);audit($pdo,'device_binding_setting',$u,['enabled'=>$enabled]);jsonOut(['success'=>true,'enabled'=>(bool)$enabled]);}
 jsonOut(['success'=>false,'error'=>'Action tidak dikenal.'],400);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log((string)$e);jsonOut(['success'=>false,'error'=>'Terjadi kesalahan server. Silakan coba kembali.'],500);}
